/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo_uas_12720;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class Menu_Utama extends javax.swing.JFrame {
    Connection conn;
    Statement stm;
            String url = "jdbc:mysql://localhost/uas_hotel_12720";
            String user = "root";
            String pass = "";

    public Menu_Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelDataTamu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Navbar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        btnTamu = new javax.swing.JMenuItem();
        btnCheckin = new javax.swing.JMenuItem();
        btnCheckout = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        lapKamarTersedia = new javax.swing.JMenuItem();
        lapKamarKosong = new javax.swing.JMenuItem();
        lapTamu = new javax.swing.JMenuItem();
        lapCheckin = new javax.swing.JMenuItem();
        lapCheckout = new javax.swing.JMenuItem();
        lapLaporanHotel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContent.setBackground(new java.awt.Color(0, 0, 0));
        panelContent.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setText("Hotel Aditya");

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel1.setText("Murah, Aman, dan Nyaman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel1)
                .addContainerGap(419, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(431, 431, 431))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        panelHome.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 780));

        panelContent.add(panelHome, "card2");

        panelDataTamu.setBackground(new java.awt.Color(0, 0, 0));
        panelDataTamu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ryuu\\Downloads\\HotelReyhan_Logo-circle-resize.png")); // NOI18N
        panelDataTamu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Check-in Hotel Reyhan");
        panelDataTamu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        panelContent.add(panelDataTamu, "card3");

        jMenu1.setText("Home");
        Navbar.add(jMenu1);

        jMenu2.setText("Data & Transaksi");

        btnTamu.setText("Data Tamu");
        btnTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamuActionPerformed(evt);
            }
        });
        jMenu2.add(btnTamu);

        btnCheckin.setText("Check-in");
        btnCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckinActionPerformed(evt);
            }
        });
        jMenu2.add(btnCheckin);

        btnCheckout.setText("Check-out");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        jMenu2.add(btnCheckout);

        Navbar.add(jMenu2);

        jMenu3.setText("Laporan");

        lapKamarTersedia.setText("Kamar Tersedia");
        lapKamarTersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapKamarTersediaActionPerformed(evt);
            }
        });
        jMenu3.add(lapKamarTersedia);

        lapKamarKosong.setText("Kamar Terisi");
        lapKamarKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapKamarKosongActionPerformed(evt);
            }
        });
        jMenu3.add(lapKamarKosong);

        lapTamu.setText("Laporan Tamu");
        lapTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapTamuActionPerformed(evt);
            }
        });
        jMenu3.add(lapTamu);

        lapCheckin.setText("Tamu Check-in");
        lapCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapCheckinActionPerformed(evt);
            }
        });
        jMenu3.add(lapCheckin);

        lapCheckout.setText("Tamu Check-out");
        lapCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapCheckoutActionPerformed(evt);
            }
        });
        jMenu3.add(lapCheckout);

        lapLaporanHotel.setText("Laporan Hotel");
        lapLaporanHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapLaporanHotelActionPerformed(evt);
            }
        });
        jMenu3.add(lapLaporanHotel);

        Navbar.add(jMenu3);

        setJMenuBar(Navbar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckinActionPerformed
        try {
            // TODO add your handling code here:
            new Check_in().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCheckinActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        try {
            // TODO add your handling code here:
            new Check_out().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void lapLaporanHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapLaporanHotelActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\PBO_UAS_12720\\src\\pbo_uas_12720\\lapHotel.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapLaporanHotelActionPerformed

    private void lapKamarTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapKamarTersediaActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\PBO_UAS_12720\\src\\pbo_uas_12720\\lapKamar.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapKamarTersediaActionPerformed

    private void lapTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapTamuActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\PBO_UAS_12720\\src\\pbo_uas_12720\\lapTamu.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapTamuActionPerformed

    private void lapCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapCheckinActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\PBO_UAS_12720\\src\\pbo_uas_12720\\lapCekIn.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapCheckinActionPerformed

    private void lapCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapCheckoutActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\PBO_UAS_12720\\src\\pbo_uas_12720\\lapCekOut.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapCheckoutActionPerformed

    private void btnTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamuActionPerformed
        try {
            // TODO add your handling code here:
            new Tamu().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Utama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTamuActionPerformed

    private void lapKamarKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapKamarKosongActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =  DriverManager.getConnection(url, user, pass);
            String reportPath = "C:\\Users\\Ryuu\\Documents\\NetBeansProjects\\PBO_UAS_12720\\src\\pbo_uas_12720\\lapAdaKamar.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
            JasperViewer.viewReport(jp);
            con.close();
            }
        catch(Exception ex) {
                   ex.printStackTrace();
               }
    }//GEN-LAST:event_lapKamarKosongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Navbar;
    private javax.swing.JMenuItem btnCheckin;
    private javax.swing.JMenuItem btnCheckout;
    private javax.swing.JMenuItem btnTamu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem lapCheckin;
    private javax.swing.JMenuItem lapCheckout;
    private javax.swing.JMenuItem lapKamarKosong;
    private javax.swing.JMenuItem lapKamarTersedia;
    private javax.swing.JMenuItem lapLaporanHotel;
    private javax.swing.JMenuItem lapTamu;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelDataTamu;
    private javax.swing.JPanel panelHome;
    // End of variables declaration//GEN-END:variables
}
