package pbo_uas_12720;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Tamu extends javax.swing.JFrame {
    Connection conn;
    Statement stm;
            String url = "jdbc:mysql://localhost/uas_hotel_12720";
            String user = "root";
            String pass = "";

    public Tamu() throws SQLException {
        initComponents();
        input_tamu(false);
        tampil_data_tamu();
        
    }
    
    void input_tamu(boolean x) {
        kodeTamu.setEnabled(x);
        namaTamu.setEnabled(x);
        alamatTamu.setEnabled(x);
        jenisKelamin.setEnabled(x);
        usiaTamu.setEnabled(x);
    }
    
    private void tampil_data_tamu() throws SQLException {
        DefaultTableModel tableTamu = new DefaultTableModel();
        
        tableTamu.addColumn("KODE TAMU");
        tableTamu.addColumn("NAMA TAMU");
        tableTamu.addColumn("JENIS KELAMIN");
        tableTamu.addColumn("USIA");
        tableTamu.addColumn("ALAMAT");
        
        tableDataTamu.setModel(tableTamu);
        
        conn = (Connection) DriverManager.getConnection(url, user, pass);
        stm = conn.createStatement();
        ResultSet dataTamu = stm .executeQuery("SELECT * FROM tamu");
        
        while (dataTamu.next()) {
            tableTamu.addRow(new Object[]{
                dataTamu.getString("Kode_tamu"),
                dataTamu.getString("Nama_tamu"),
                dataTamu.getString("Jns_kel"),
                dataTamu.getString("Usia"),
                dataTamu.getString("alamat")
            });
        }
    }
    
    private void kosongkan_input() {
        kodeTamu.setText("");
        namaTamu.setText("");
        usiaTamu.setText("");
        alamatTamu.setText("");
        
        kodeTamu.requestFocus();
    }
    
    private void simpan_data_tamu() throws SQLException {
        conn = (Connection) DriverManager.getConnection(url, user, pass);
        PreparedStatement pstm = conn.prepareStatement("INSERT INTO tamu"
                + " (Kode_tamu, Nama_tamu, Jns_kel, Usia, alamat)"
                + " VALUES ('"+kodeTamu.getText()+"', '"+namaTamu.getText()+"', '"+jenisKelamin.getSelectedItem()+"', '"+usiaTamu.getText()+"',"
                        + " '"+alamatTamu.getText()+"')");
        tampil_data_tamu();
        
        if ( pstm.executeUpdate() > 0) {
            JOptionPane.showMessageDialog(this, "Simpan Data Tamu Sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Simpan Data Tamu Gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            pstm.close();
        }
    }
    
    private void ubah_data_tamu() throws SQLException {
        conn = (Connection) DriverManager.getConnection(url, user, pass);
        PreparedStatement pstm = conn.prepareStatement("UPDATE tamu SET "
                + "Kode_tamu = '"+kodeTamu.getText()+"', Nama_tamu = '"+namaTamu.getText()+"', Jns_kel = '"+jenisKelamin.getSelectedItem()+"', Usia = '"+usiaTamu.getText()+"',"
                + "alamat = '"+alamatTamu.getText()+"' WHERE Kode_tamu = '"+kodeTamu.getText()+"'");
        
        if ( pstm.executeUpdate() > 0) {
            JOptionPane.showMessageDialog(this, "Ubah Data Sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        judulCheckin = new javax.swing.JLabel();
        panelTamu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kodeTamu = new javax.swing.JTextField();
        namaTamu = new javax.swing.JTextField();
        alamatTamu = new javax.swing.JTextField();
        usiaTamu = new javax.swing.JTextField();
        jenisKelamin = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataTamu = new javax.swing.JTable();
        panelButton = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnInput = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        judulCheckin1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 51, 255));

        judulCheckin.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        judulCheckin.setText("Data Tamu Hotel Aditya");

        panelTamu.setBackground(new java.awt.Color(255, 255, 255));
        panelTamu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kode Tamu");
        panelTamu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama");
        panelTamu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("L/P");
        panelTamu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Umur");
        panelTamu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Alamat");
        panelTamu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        kodeTamu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kodeTamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kodeTamuKeyPressed(evt);
            }
        });
        panelTamu.add(kodeTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 170, -1));

        namaTamu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTamuActionPerformed(evt);
            }
        });
        namaTamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaTamuKeyPressed(evt);
            }
        });
        panelTamu.add(namaTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 310, -1));

        alamatTamu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alamatTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatTamuActionPerformed(evt);
            }
        });
        alamatTamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alamatTamuKeyPressed(evt);
            }
        });
        panelTamu.add(alamatTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 310, -1));

        usiaTamu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usiaTamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usiaTamuKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usiaTamuKeyTyped(evt);
            }
        });
        panelTamu.add(usiaTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 60, -1));

        jenisKelamin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));
        panelTamu.add(jenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 50, -1));

        tableDataTamu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableDataTamu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDataTamu);

        panelButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelButton.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 90, 40));

        btnInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInput.setText("INPUT");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        panelButton.add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 40));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        panelButton.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 100, 40));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelButton.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 100, 40));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelButton.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 100, 40));

        judulCheckin1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        judulCheckin1.setText("Input Data Tamu");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTamu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                                .addComponent(judulCheckin)
                                .addGap(186, 186, 186))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                                .addComponent(judulCheckin1)
                                .addGap(265, 265, 265))))))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judulCheckin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(judulCheckin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTamuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTamuActionPerformed

    private void alamatTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatTamuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatTamuActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        input_tamu(true);
    }//GEN-LAST:event_btnInputActionPerformed

    private void usiaTamuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usiaTamuKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if ( c != KeyEvent.VK_ENTER ) {
            if (! ((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Masukkan hanya angka 0-9 !");
                evt.consume();
            }
        }
    }//GEN-LAST:event_usiaTamuKeyTyped

    private void kodeTamuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeTamuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if( kodeTamu.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Error: Kode Tamu Tidak Boleh Kosong !", 
                    "Error !", JOptionPane.WARNING_MESSAGE);    
            } else {
                    namaTamu.requestFocus();
                }
        }
    }//GEN-LAST:event_kodeTamuKeyPressed

    private void namaTamuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaTamuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if( namaTamu.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Error: Nama Tamu Tidak Boleh Kosong !", 
                    "Error !", JOptionPane.WARNING_MESSAGE);    
            } else {
                    alamatTamu.requestFocus();
                }
        }
    }//GEN-LAST:event_namaTamuKeyPressed

    private void alamatTamuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alamatTamuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if( alamatTamu.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Error: Alamat Tidak Boleh Kosong !", 
                    "Error !", JOptionPane.WARNING_MESSAGE);    
            } else {
                    jenisKelamin.requestFocus();
                }
        }
    }//GEN-LAST:event_alamatTamuKeyPressed

    private void usiaTamuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usiaTamuKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if( namaTamu.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Error: Usia Tamu Tidak Boleh Kosong !", 
                    "Error !", JOptionPane.WARNING_MESSAGE);    
            }
        }
    }//GEN-LAST:event_usiaTamuKeyPressed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // TODO add your handling code here:
            if( kodeTamu.getText().isEmpty() || namaTamu.getText().isEmpty() || alamatTamu.getText().isEmpty() || usiaTamu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: Mohon Lengkapi Kolom Isian !", 
                    "Error !", JOptionPane.WARNING_MESSAGE);    
            } else {
                simpan_data_tamu();
                kosongkan_input();
                tampil_data_tamu();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Tamu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            if( kodeTamu.getText().isEmpty() ) {
                JOptionPane.showMessageDialog(null, "Error: Kode Tamu tidak boleh kosong !", 
                        "Error !", JOptionPane.WARNING_MESSAGE);
            } else {
                conn = (Connection) DriverManager.getConnection(url, user, pass);
                stm = conn.createStatement();
                PreparedStatement pstm = conn.prepareStatement("DELETE FROM tamu WHERE Kode_tamu = '"+kodeTamu.getText()+"'");
        
        if ( pstm.executeUpdate() > 0) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        tampil_data_tamu();
        kosongkan_input();
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Kesalahan " + err);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int reply =JOptionPane.showConfirmDialog(
                null, 
                "Apakah Anda yakin ingin keluar aplikasi ?", 
                "Konfirmasi Keluar Aplikasi", 
                JOptionPane.YES_NO_OPTION);
        
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            if( kodeTamu.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Error: Kode Tamu tidak boleh kosong !", 
                        "Error !", JOptionPane.WARNING_MESSAGE);
            }
            ubah_data_tamu();
            tampil_data_tamu();
            
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Kesalahan " + err);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tamu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tamu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTamu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenisKelamin;
    private javax.swing.JLabel judulCheckin;
    private javax.swing.JLabel judulCheckin1;
    private javax.swing.JTextField kodeTamu;
    private javax.swing.JTextField namaTamu;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelTamu;
    private javax.swing.JTable tableDataTamu;
    private javax.swing.JTextField usiaTamu;
    // End of variables declaration//GEN-END:variables
}
